import Menu from "@/components/shared/header/Menu";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import MainNav from "./MainNav";


const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <div className="flex flex-col max-w-7xl mx-auto">
            <div className="border-b">
                <div className="flex items-center h-16 px-4">
                    <Link href="/">
                        <Image
                            src="/images/logo.svg"
                            alt="logo"
                            width={48}
                            height={48}
                        />
                    </Link>
                    <MainNav className="mx-6" />
                    <div className="ml-auto flex items-baseline space-x-4">
                        <Menu />
                    </div>
                </div>
            </div>
            <main className="flex-1 p-8">{children}</main>
        </div>
    </>
  );
}
